### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LoYungSum** [ItsMennyo/Flex-AntiCheat#5]
Every time you post a config, there will be two version, one with "#Default: true", and another one with no "#Default: true"

Use of this: I don't want to know about the default value, sometimes it is useless.

**Comment by ItsMennyo** [comment]
The reason why I always put that in the config is for basic troubleshooting. This config does not work equally well for every server. This tells the owner what the original value is to play with it to make it work better for their server.

I already removed the unnecessary notes from the AntiAura config to reduce the config size. But for most settings, I just leave it there because of what I said above.
